;;; themian-theme.el --- My color theme

;;; Commentary:

;;; Code:

(defgroup themian nil
  "Faces for the themian theme"
  :prefix "themian-face-"
  :group 'faces)

;; XXX force re-eval of defcustom form
;; (when (featurep 'themian-theme)
;;   (makunbound 'themian-force-fixed-faces))

(defcustom themian-force-fixed-faces
  '(company-echo
    company-echo-common
    company-preview
    ;; keep this variable pitched as it's used on the same line as the input
    ;; text (which is variable).
    ;; company-preview-common
    company-preview-search
    company-scrollbar-bg
    company-scrollbar-fg
    company-template-field
    company-tooltip
    company-tooltip-annotation
    company-tooltip-annotation-selection
    company-tooltip-common
    company-tooltip-common-selection
    company-tooltip-mouse
    company-tooltip-search
    company-tooltip-search-selection
    company-tooltip-selection
    line-number
    line-number-current-line
    linum
    linum-relative-current-face
    org-block
    org-block-begin-line
    org-block-end-line
    org-checkbox
    org-code
    org-column
    org-column-title
    org-date
    org-document-info-keyword
    org-drawer
    org-formula
    org-hide
    org-indent
    org-link
    org-meta-line
    org-property-value
    org-special-keyword
    org-table
    org-verbatim
    whitespace-indentation
    whitespace-hspace
    whitespace-space
    whitespace-tab)
  "Ensure each specified face inherits from `fixed-pitch'. This is to support `themian-org-mode-variable-pitch'."
  :group 'themian
  :type '((repeat (restricted-sexp :match-alternatives (facep)))))

(defcustom themian-org-mode-variable-pitch t
  "When set, make use of `variable-pitch' face when in `org-mode'.

Note: `variable-pitch' must have it's font set before enabling this theme and `buffer-face-mode' must be enabled for this to take effect.

See `themian-force-fixed-faces' for a list of faces that should remain fixed width."
  :group 'themian
  :type '(boolean))

(defcustom themian-org-mode-emphasize-todo t
  "When set, org todo items have extra emphasis.")


(defface themian-error nil
  "Face for critical information"
  :group 'themian)

(defface themian-heading nil
  "Face for headers"
  :group 'themian)

(defface themian-important nil
  "Face for highlighting important information"
  :group 'themian)

(defface themian-item nil
  "Face for items (lists, elements, etc)"
  :group 'themian)

(defface themian-match nil
  "Face for search selections"
  :group 'themian)

(defface themian-selected nil
  "Face for selected items"
  :group 'themian)

(defface themian-strong nil
  "Face used for emphasis"
  :group 'themian)

(defface themian-subtle nil
  "Face for subtle information (de-de-emphasis)"
  :group 'themian)

(defface themian-unknown nil
  "Face for unstyled faces (only for theme development)"
  :group 'themian)

(defface themian-warning nil
  "Face for important information"
  :group 'themian)

(defface themian-weak nil
  "Face used for de-emphasis"
  :group 'themian)

(defvar themian--show-unknowns nil
  "Show unset faces as right pink.")


(defmacro themian--with-color-variables (variant &rest body)
  "Expose my color theme variables. `blue', `base-4', etc."
  (declare (indent 1))
  `(let* ((dark (eq ,variant 'dark))
          (unknown  "#9933ff")
          ;; The following is generated automatically from colorwheel.py
          ;;;; THEMIAN-COLORS-START
          (base+1       (if dark "#94989e" "#857547"))
          (base+2       (if dark "#bcbfc2" "#53492d"))
          (base+3       (if dark "#d7d8db" "#2e2a1f"))
          (base+4       (if dark "#e4e5e7" "#1c1b17"))
          (base-1       (if dark "#61656b" "#baa35e"))
          (base-2       (if dark "#3d3f43" "#c9b882"))
          (base-3       (if dark "#242628" "#e5d9b2"))
          (base-4       (if dark "#18191b" "#f7eed4"))
          (base-5       (if dark "#111213" "#fdf5dd"))
          (blue         (if dark "#7596c8" "#37588a"))
          (blue-bg      (if dark "#37588a" "#7596c8"))
          (cyan         (if dark "#75c8c3" "#378a85"))
          (cyan-bg      (if dark "#378a85" "#75c8c3"))
          (diff-1       (if dark "#1d4946" "#92d3cf"))
          (diff-2       (if dark "#33807a" "#5bbdb7"))
          (diff-3       (if dark "#071211" "#c8e9e7"))
          (diff-4       (if dark "#1d4946" "#92d3cf"))
          (green        (if dark "#7ac875" "#3c8a37"))
          (green-bg     (if dark "#3c8a37" "#7ac875"))
          (magenta      (if dark "#c875b2" "#8a3774"))
          (magenta-bg   (if dark "#8a3774" "#c875b2"))
          (orange       (if dark "#c8b575" "#8a7737"))
          (orange-bg    (if dark "#8a7737" "#c8b575"))
          (red          (if dark "#c87588" "#8a374a"))
          (red-bg       (if dark "#8a374a" "#c87588"))
          (violet       (if dark "#8b75c8" "#4d378a"))
          (violet-bg    (if dark "#4d378a" "#8b75c8"))
          (yellow       (if dark "#bfc875" "#818a37"))
          (yellow-bg    (if dark "#818a37" "#bfc875"))
          ;;;; THEMIAN-COLORS-END
          )
     ,@body))


(defun themian--to-color-theme (forms)
  "Take a list of FORMS and translate them into a suitable format for
`custom-theme-set-faces'. Each form should be of the format: (FACE ATTRIBUTES)."
  (let* ((class '((class color) (min-colors 89)))
         (default-attributes
           '(:family unspecified
             :foundry unspecified
             :width unspecified
             :height unspecified
             :weight unspecified
             :slant unspecified
             :foreground unspecified
             :distant-foreground unspecified
             :background unspecified
             :underline unspecified
             :overline unspecified
             :strike-through unspecified
             :box unspecified
             :inverse unspecified
             :stipple unspecified
             :font unspecified
             :fontset unspecified
             :extend unspecified
             :inherit unspecified)))
    (mapcar
     (lambda (config)
       (let ((face (nth 0 config))
             (attrs (nth 1 config)))
         (themian--merge-plists attrs default-attributes)
         `(,face (,(cons class attrs)))))
     forms)))


(defun themian--unroll-parents (forms)
  "Unroll any parents found for each face so that the attributes are set in each
specified face, skipping runtime inheritance. Each form in FORMS should be of
the format: (FACE PARENTS &optional ATTRIBUTES)."
  (let ((expanded (make-hash-table))
        (unexpanded (make-hash-table))
        faces
        return-value)
    (mapc (lambda (form)
            (let* ((face (nth 0 form))
                   (parents (nth 1 form))
                   (attrs (nth 2 form)))
              (puthash face (cons parents attrs) unexpanded)
              (push face faces)))
          forms)
    (mapc (lambda (face)
               (push (list face (themian--unroll-face expanded unexpanded face))
                     return-value))
             faces)
    return-value))


(defun themian--unroll-face (expanded unexpanded face)
  "Unroll FACE, setting it's attributes in EXPANDED hash table; unrolling any
parents from UNEXPANDED hash table."
  (if-let ((value (gethash face expanded)))
      value
    (let* ((form (gethash face unexpanded))
           (parents (car form))
           (attrs (cdr form)))
      ;; ensure parents is a list
      (unless (listp parents)
        (setq parents (list parents)))
      ;; possible inherit from 'fixed-pitch
      (when (member face themian-force-fixed-faces)
        (setq attrs (append '(:inherit fixed-pitch) attrs)))
      (remhash face unexpanded)
      (puthash face
               (apply
                #'themian--merge-plists
                attrs
                (mapcar (lambda (p)
                          (themian--unroll-face expanded unexpanded p))
                        parents))
               expanded))))


(defun themian--merge-plists (dest &rest sources)
  "Merge each plist found in SOURCES into DEST, skipping any key already
set. Modifies DEST in-place. Each plist in SOURCES must be well formed."
  (mapc
   (lambda (plist)
     (while plist
       (let ((prop (pop plist))
             (val (pop plist)))
         (unless (plist-member dest prop)
           (setf dest (plist-put dest prop val))))))
   sources)
  dest)


(defun themian-create-color-theme (theme-name variant)
  (apply
   #'custom-theme-set-faces
   theme-name
   (themian--to-color-theme
    (themian--unroll-parents
     (themian--with-color-variables variant
       `(;; each face is of the format: (FACE &optional PARENTS ATTRIBUTES)

         ;; default face
         (default nil ,(append (face-attr-construct 'default)
                               `(:foreground ,base+3 :background ,base-4)))

         ;; themian faces
         (themian-error nil (:foreground ,red :weight bold))
         (themian-heading nil (:foreground ,orange :height 1.2 :inherit variable-pitch))
         (themian-important themian-strong (:background ,base-3))
         (themian-item nil (:foreground ,blue))
         (themian-match nil (:foreground ,green :weight bold))
         (themian-selected nil (:foreground ,orange :background ,base-5 :weight bold))
         (themian-strong nil (:foreground ,base+4 :weight bold))
         (themian-subtle nil (:foreground ,base-1 :weight light :slant italic))
         (themian-unknown nil ,(when themian--show-unknowns `(:background ,unknown)))
         (themian-warning nil (:foreground ,yellow :weight bold))
         (themian-weak nil (:foreground ,base+1 :weight light))

         ;; core faces
         (button nil (:foreground ,base+4 :background ,base-2
                                  :box (:line-width 1 :style released-button)))
         (cursor nil (:background ,cyan))
         (error themian-error)
         (escape-glyph nil (:foreground ,base+3 :background ,base-2 :weight bold))
         (font-lock-builtin-face nil (:foreground ,blue))
         (font-lock-comment-delimiter-face font-lock-comment-face)
         (font-lock-comment-face nil (:foreground ,cyan :slant italic))
         (font-lock-constant-face nil (:foreground ,green))
         (font-lock-doc-face nil (:foreground ,green))
         (font-lock-function-name-face nil (:foreground ,blue :weight bold))
         (font-lock-keyword-face nil (:foreground ,orange :weight light :slant italic))
         (font-lock-negation-char-face nil (:inherit default))
         (font-lock-preprocessor-face nil (:foreground ,orange))
         (font-lock-regexp-grouping-backslash nil (:foreground ,base+1))
         (font-lock-regexp-grouping-construct nil (:foreground ,base+2))
         (font-lock-string-face nil (:foreground ,base+2))
         (font-lock-type-face nil (:foreground ,green :slant italic))
         (font-lock-variable-name-face nil (:foreground ,base+4))
         (font-lock-warning-face themian-warning)
         (fringe nil (:foreground ,base+1 :background ,base-5))
         (header-line themian-heading (:background ,base-3))
         (header-line-highlight themian-unknown)
         (highlight nil (:background ,base-3))
         (hl-line highlight)
         (isearch themian-match)
         (isearch-fail themian-warning)
         (lazy-highlight region (:background ,base-2))
         (link nil (:weight bold :underline t))
         (link-visited link)
         (line-number themian-subtle (:background ,base-5))
         (line-number-current-line themian-strong)
         (linum line-number)
         (linum-relative-current-face line-number-current-line)
         (match themian-match)
         (minibuffer-prompt themian-strong)
         (region nil (:background ,base-2))
         (secondary-selection nil (:background ,base-3))
         (success themian-unknown)
         (shadow themian-subtle)
         (tooltip themian-unknown)
         (trailing-whitespace themian-warning)
         (vertical-border nil (:foreground ,base-1))
         (warning themian-warning)

         ;; extra tree-sitter faces
         ;; (customize-set-variable 'treesit-font-lock-level 4)
         (font-lock-bracket-face nil (:foreground ,base+2))
         (font-lock-delimiter-face nil (:foreground ,base+2))
         (font-lock-doc-markup-face nil (:foreground ,unknown))
         (font-lock-escape-face font-lock-string-face (:weight bold))
         (font-lock-function-call-face nil (:foreground ,base+4))
         (font-lock-misc-punctuation-face nil (:foreground ,unknown))
         (font-lock-number-face nil (:foreground ,green))
         (font-lock-operator-face nil (:foreground ,base+2))
         (font-lock-property-name-face nil (:foreground ,base+4))
         (font-lock-property-use-face nil (:foreground ,base+4))
         (font-lock-punctuation-face nil (:foreground ,unknown))
         (font-lock-regexp-face nil (:foreground ,orange :background ,base-4))
         (font-lock-variable-use-face nil)

         ;; rest faces
         ;; (Info-quoted themian-unknown)
         (auto-dim-other-buffers-face nil (:background ,base-5))
         (auto-dim-other-buffers-hide-face nil (:foreground ,base-5 :background ,base-5))
         (bookmark-menu-bookmark (themian-item themian-strong))
         (bookmark-menu-heading themian-heading)
         ;; (border themian-unknown)
         ;; (browse-url-button themian-unknown)
         ;; (buffer-menu-buffer themian-unknown)
         ;; (calc-nonselected-face themian-unknown)
         ;; (calc-selected-face themian-unknown)
         ;; (calendar-month-header themian-unknown)
         ;; (calendar-today themian-unknown)
         ;; (calendar-weekday-header themian-unknown)
         ;; (calendar-weekend-header themian-unknown)
         ;; (change-log-acknowledgment themian-unknown)
         ;; (change-log-conditionals themian-unknown)
         ;; (change-log-date themian-unknown)
         ;; (change-log-email themian-unknown)
         ;; (change-log-file themian-unknown)
         ;; (change-log-function themian-unknown)
         ;; (change-log-list themian-unknown)
         ;; (change-log-name themian-unknown)
         ;; (comint-highlight-input themian-unknown)
         ;; (comint-highlight-prompt themian-unknown)
         (company-echo themian-unknown)
         (company-echo-common themian-unknown)
         (company-preview nil)
         (company-preview-common themian-weak)
         (company-preview-search themian-unknown)
         (company-scrollbar-bg nil (:background ,base-3))
         (company-scrollbar-fg nil (:background ,base+1))
         (company-template-field themian-unknown)
         (company-tooltip nil (:background ,base-5))
         (company-tooltip-annotation (themian-item themian-weak))
         (company-tooltip-annotation-selection company-tooltip-annotation)
         (company-tooltip-common themian-match)
         (company-tooltip-common-selection company-tooltip-common)
         (company-tooltip-mouse highlight)
         (company-tooltip-search themian-unknown)
         (company-tooltip-search-selection themian-unknown)
         (company-tooltip-selection highlight)
         ;; (compilation-column-number themian-unknown)
         ;; (compilation-error themian-unknown)
         ;; (compilation-info themian-unknown)
         ;; (compilation-line-number themian-unknown)
         ;; (compilation-mode-line-exit themian-unknown)
         ;; (compilation-mode-line-fail themian-unknown)
         ;; (compilation-mode-line-run themian-unknown)
         ;; (compilation-warning themian-unknown)
         ;; (completions-annotations themian-unknown)
         ;; (completions-common-part themian-unknown)
         ;; (completions-first-difference themian-unknown)
         ;; (cua-global-mark themian-unknown)
         ;; (cua-rectangle themian-unknown)
         ;; (cua-rectangle-noselect themian-unknown)
         ;; (custom-button themian-unknown)
         ;; (custom-button-mouse themian-unknown)
         ;; (custom-button-pressed themian-unknown)
         ;; (custom-button-pressed-unraised themian-unknown)
         ;; (custom-button-unraised themian-unknown)
         ;; (custom-changed themian-unknown)
         ;; (custom-comment themian-unknown)
         ;; (custom-comment-tag themian-unknown)
         ;; (custom-documentation themian-unknown)
         ;; (custom-face-tag themian-unknown)
         ;; (custom-group-subtitle themian-unknown)
         ;; (custom-group-tag themian-unknown)
         ;; (custom-group-tag-1 themian-unknown)
         ;; (custom-invalid themian-unknown)
         ;; (custom-link themian-unknown)
         ;; (custom-modified themian-unknown)
         ;; (custom-rogue themian-unknown)
         ;; (custom-saved themian-unknown)
         ;; (custom-set themian-unknown)
         ;; (custom-state themian-unknown)
         ;; (custom-themed themian-unknown)
         ;; (custom-variable-button themian-unknown)
         ;; (custom-variable-obsolete themian-unknown)
         ;; (custom-variable-tag themian-unknown)
         ;; (custom-visibility themian-unknown)
         ;; (diary themian-unknown)
         ;; (diary-anniversary themian-unknown)
         ;; (diary-button themian-unknown)
         ;; (diary-time themian-unknown)
         (diff-added nil (:background ,green-bg))
         ;; (diff-changed themian-unknown)
         (diff-context nil)
         ;; (diff-error themian-unknown)
         ;; (diff-file-header themian-unknown)
         ;; (diff-function themian-unknown)
         ;; (diff-header themian-unknown)
         ;; (diff-hunk-header themian-unknown)
         ;; (diff-index themian-unknown)
         ;; (diff-indicator-added themian-unknown)
         ;; (diff-indicator-changed themian-unknown)
         ;; (diff-indicator-removed themian-unknown)
         ;; (diff-nonexistent themian-unknown)
         ;; (diff-refine-added themian-unknown)
         ;; (diff-refine-changed themian-unknown)
         ;; (diff-refine-removed themian-unknown)
         (diff-removed nil (:background ,red-bg))
         (dired-broken-symlink themian-error)
         (dired-directory themian-strong (:foreground ,blue))
         (dired-flagged themian-error)
         (dired-header themian-heading)
         (dired-ignored themian-subtle)
         (dired-mark themian-strong (:foreground ,orange))
         (dired-marked themian-important)
         (dired-perm-write themian-warning)
         (dired-set-id themian-warning)
         (dired-special themian-strong (:foreground ,yellow))
         (dired-symlink themian-strong (:foreground ,cyan))
         (dired-warning themian-warning)
         ;; (edebug-disabled-breakpoint themian-unknown)
         ;; (edebug-enabled-breakpoint themian-unknown)
         ;; (eldoc-highlight-function-argument themian-unknown)
         ;; (epa-field-body themian-unknown)
         ;; (epa-field-name themian-unknown)
         ;; (epa-mark themian-unknown)
         ;; (epa-string themian-unknown)
         ;; (epa-validity-disabled themian-unknown)
         ;; (epa-validity-high themian-unknown)
         ;; (epa-validity-low themian-unknown)
         ;; (epa-validity-medium themian-unknown)
         (evil-ex-commands themian-unknown)
         (evil-ex-info themian-warning)
         (evil-ex-lazy-highlight lazy-highlight)
         (evil-ex-search themian-match)
         (evil-ex-substitute-matches (themian-match themian-important))
         (evil-ex-substitute-replacement themian-strong)
         ;; (eww-form-checkbox themian-unknown)
         ;; (eww-form-file themian-unknown)
         ;; (eww-form-select themian-unknown)
         ;; (eww-form-submit themian-unknown)
         ;; (eww-form-text themian-unknown)
         ;; (eww-form-textarea themian-unknown)
         ;; (eww-invalid-certificate themian-unknown)
         ;; (eww-valid-certificate themian-unknown)
         ;; (ffap themian-unknown)
         ;; (file-name-shadow themian-unknown)
         ;; (fill-column-indicator themian-unknown)
         ;; (fixed-pitch themian-unknown)
         ;; (fixed-pitch-serif themian-unknown)
         ;; (flymake-error themian-unknown)
         ;; (flymake-note themian-unknown)
         ;; (flymake-warning themian-unknown)
         ;; (flyspell-duplicate themian-unknown)
         ;; (flyspell-incorrect themian-unknown)
         ;; (git-commit-comment-action themian-unknown)
         ;; (git-commit-comment-branch-local themian-unknown)
         ;; (git-commit-comment-branch-remote themian-unknown)
         ;; (git-commit-comment-detached themian-unknown)
         ;; (git-commit-comment-file themian-unknown)
         ;; (git-commit-comment-heading themian-unknown)
         ;; (git-commit-keyword themian-unknown)
         ;; (git-commit-known-pseudo-header themian-unknown)
         ;; (git-commit-nonempty-second-line themian-unknown)
         ;; (git-commit-overlong-summary themian-unknown)
         ;; (git-commit-pseudo-header themian-unknown)
         ;; (git-commit-summary themian-unknown)
         ;; (glyphless-char themian-unknown)
         ;; (gnus-group-mail-1 themian-unknown)
         ;; (gnus-group-mail-1-empty themian-unknown)
         ;; (gnus-group-mail-2 themian-unknown)
         ;; (gnus-group-mail-2-empty themian-unknown)
         ;; (gnus-group-mail-3 themian-unknown)
         ;; (gnus-group-mail-3-empty themian-unknown)
         ;; (gnus-group-mail-low themian-unknown)
         ;; (gnus-group-mail-low-empty themian-unknown)
         ;; (gnus-group-news-1 themian-unknown)
         ;; (gnus-group-news-1-empty themian-unknown)
         ;; (gnus-group-news-2 themian-unknown)
         ;; (gnus-group-news-2-empty themian-unknown)
         ;; (gnus-group-news-3 themian-unknown)
         ;; (gnus-group-news-3-empty themian-unknown)
         ;; (gnus-group-news-4 themian-unknown)
         ;; (gnus-group-news-4-empty themian-unknown)
         ;; (gnus-group-news-5 themian-unknown)
         ;; (gnus-group-news-5-empty themian-unknown)
         ;; (gnus-group-news-6 themian-unknown)
         ;; (gnus-group-news-6-empty themian-unknown)
         ;; (gnus-group-news-low themian-unknown)
         ;; (gnus-group-news-low-empty themian-unknown)
         ;; (gnus-splash themian-unknown)
         ;; (gnus-summary-cancelled themian-unknown)
         ;; (gnus-summary-high-ancient themian-unknown)
         ;; (gnus-summary-high-read themian-unknown)
         ;; (gnus-summary-high-ticked themian-unknown)
         ;; (gnus-summary-high-undownloaded themian-unknown)
         ;; (gnus-summary-high-unread themian-unknown)
         ;; (gnus-summary-low-ancient themian-unknown)
         ;; (gnus-summary-low-read themian-unknown)
         ;; (gnus-summary-low-ticked themian-unknown)
         ;; (gnus-summary-low-undownloaded themian-unknown)
         ;; (gnus-summary-low-unread themian-unknown)
         ;; (gnus-summary-normal-ancient themian-unknown)
         ;; (gnus-summary-normal-read themian-unknown)
         ;; (gnus-summary-normal-ticked themian-unknown)
         ;; (gnus-summary-normal-undownloaded themian-unknown)
         ;; (gnus-summary-normal-unread themian-unknown)
         ;; (gnus-summary-selected themian-unknown)
         ;; (haskell-constructor-face themian-unknown)
         ;; (haskell-debug-heading-face themian-unknown)
         ;; (haskell-debug-keybinding-face themian-unknown)
         ;; (haskell-debug-muted-face themian-unknown)
         ;; (haskell-debug-newline-face themian-unknown)
         ;; (haskell-debug-trace-number-face themian-unknown)
         ;; (haskell-debug-warning-face themian-unknown)
         ;; (haskell-definition-face themian-unknown)
         ;; (haskell-error-face themian-unknown)
         ;; (haskell-hole-face themian-unknown)
         ;; (haskell-interactive-face-compile-error themian-unknown)
         ;; (haskell-interactive-face-compile-warning themian-unknown)
         ;; (haskell-interactive-face-garbage themian-unknown)
         ;; (haskell-interactive-face-prompt themian-unknown)
         ;; (haskell-interactive-face-prompt-cont themian-unknown)
         ;; (haskell-interactive-face-result themian-unknown)
         ;; (haskell-keyword-face themian-unknown)
         ;; (haskell-liquid-haskell-annotation-face themian-unknown)
         ;; (haskell-literate-comment-face themian-unknown)
         ;; (haskell-operator-face themian-unknown)
         ;; (haskell-pragma-face themian-unknown)
         ;; (haskell-quasi-quote-face themian-unknown)
         ;; (haskell-type-face themian-unknown)
         ;; (haskell-warning-face themian-unknown)
         (helm-M-x-key button)
         (helm-action themian-item)
         (helm-bookmark-addressbook themian-unknown)
         (helm-bookmark-directory themian-unknown)
         (helm-bookmark-file themian-unknown)
         (helm-bookmark-file-not-found themian-unknown)
         (helm-bookmark-gnus themian-unknown)
         (helm-bookmark-info themian-unknown)
         (helm-bookmark-man themian-unknown)
         (helm-bookmark-w3m themian-unknown)
         (helm-buffer-archive themian-unknown)
         (helm-buffer-directory dired-directory)
         (helm-buffer-file nil)
         (helm-buffer-modified themian-strong (:slant italic))
         (helm-buffer-not-saved helm-buffer-modified)
         (helm-buffer-process themian-item)
         (helm-buffer-saved-out themian-warning)
         (helm-buffer-size themian-subtle)
         (helm-candidate-number themian-unknown)
         (helm-candidate-number-suspended themian-unknown)
         (helm-command-active-mode themian-warning)
         (helm-delete-async-message themian-unknown)
         (helm-eob-line nil (:background ,base-5))
         (helm-etags-file themian-unknown)
         (helm-ff-backup-file themian-weak)
         (helm-ff-denied themian-unknown)
         (helm-ff-directory dired-directory)
         (helm-ff-dirs themian-unknown)
         (helm-ff-dotted-directory themian-subtle)
         (helm-ff-dotted-symlink-directory themian-unknown)
         (helm-ff-executable themian-strong (:foreground ,green))
         (helm-ff-file nil)
         (helm-ff-file-extension themian-weak)
         (helm-ff-invalid-symlink dired-broken-symlink)
         (helm-ff-pipe dired-special)
         (helm-ff-prefix themian-subtle)
         (helm-ff-rsync-progress themian-unknown)
         (helm-ff-socket themian-strong (:foreground ,magenta))
         (helm-ff-suid dired-set-id)
         (helm-ff-symlink dired-symlink)
         (helm-ff-truename themian-weak)
         (helm-grep-cmd-line themian-strong)
         (helm-grep-file themian-weak)
         (helm-grep-finish themian-strong)
         (helm-grep-lineno line-number)
         (helm-grep-match themian-match)
         (helm-header themian-weak (:height 0.8 :overline ,base-1))
         (helm-header-line-left-margin themian-unknown)
         (helm-helper themian-unknown)
         (helm-history-deleted themian-unknown)
         (helm-history-remote themian-unknown)
         (helm-lisp-completion-info themian-unknown)
         (helm-lisp-show-completion themian-unknown)
         (helm-locate-finish helm-grep-finish)
         (helm-match themian-match)
         (helm-match-item themian-match)
         (helm-minibuffer-prompt minibuffer-prompt)
         (helm-moccur-buffer (themian-item helm-grep-lineno))
         (helm-mode-prefix themian-unknown)
         (helm-no-file-buffer-modified themian-unknown)
         (helm-non-file-buffer nil (:weight light))
         (helm-ol-author themian-strong)
         (helm-ol-editions themian-subtle)
         (helm-ol-seperator themian-weak)
         (helm-ol-title themian-item)
         (helm-prefarg themian-unknown)
         (helm-resume-need-update themian-warning)
         ;; (helm-rg-active-arg-face themian-strong)
         ;; (helm-rg-base-rg-cmd-face themian-weak)
         ;; (helm-rg-colon-separator-ripgrep-output-face themian-subtle)
         ;; (helm-rg-directory-cmd-face themian-unknown)
         ;; (helm-rg-directory-header-face themian-unknown)
         ;; (helm-rg-error-message themian-unknown)
         ;; (helm-rg-extra-arg-face themian-unknown)
         (helm-rg-file-match-face helm-grep-file)
         ;; (helm-rg-inactive-arg-face themian-unknown)
         (helm-rg-line-number-match-face helm-grep-lineno)
         ;; (helm-rg-match-text-face themian-unknown)
         ;; (helm-rg-preview-line-highlight themian-unknown)
         ;; (helm-rg-title-face themian-unknown)
         (helm-selection highlight)
         (helm-selection-line highlight)
         (helm-separator themian-subtle)
         (helm-source-header themian-heading (:background ,base-5))
         (helm-ucs-char font-lock-constant-face)
         (helm-visible-mark themian-selected)
         ;; (help-argument-name themian-unknown)
         ;; (holiday themian-unknown)
         ;; (homoglyph themian-unknown)
         ;; (ibuffer-locked-buffer themian-unknown)
         ;; (info-header-node themian-unknown)
         ;; (info-header-xref themian-unknown)
         ;; (info-index-match themian-unknown)
         ;; (info-menu-header themian-unknown)
         ;; (info-menu-star themian-unknown)
         ;; (info-node themian-unknown)
         ;; (info-title-1 themian-unknown)
         ;; (info-title-2 themian-unknown)
         ;; (info-title-3 themian-unknown)
         ;; (info-title-4 themian-unknown)
         ;; (info-xref themian-unknown)
         ;; (info-xref-visited themian-unknown)
         ;; (internal-border themian-unknown)
         ;; (line-number-major-tick themian-unknown)
         ;; (line-number-minor-tick themian-unknown)
         ;; (log-edit-header themian-unknown)
         ;; (log-edit-summary themian-unknown)
         ;; (log-edit-unknown-header themian-unknown)
         ;; (lsp-details-face themian-unknown)
         ;; (lsp-face-highlight-read themian-unknown)
         ;; (lsp-face-highlight-textual themian-unknown)
         ;; (lsp-face-highlight-write themian-unknown)
         ;; (lsp-face-rename themian-unknown)
         ;; (lsp-installation-buffer-face themian-unknown)
         ;; (lsp-installation-finished-buffer-face themian-unknown)
         ;; (lsp-rename-placeholder-face themian-unknown)
         ;; (lsp-signature-face themian-unknown)
         ;; (lsp-signature-posframe themian-unknown)
         ;; (lv-separator themian-unknown)
         ;; (magit-bisect-bad themian-unknown)
         ;; (magit-bisect-good themian-unknown)
         ;; (magit-bisect-skip themian-unknown)
         ;; (magit-blame-date themian-unknown)
         ;; (magit-blame-dimmed themian-unknown)
         ;; (magit-blame-hash themian-unknown)
         ;; (magit-blame-heading themian-unknown)
         ;; (magit-blame-highlight themian-unknown)
         ;; (magit-blame-margin themian-unknown)
         ;; (magit-blame-name themian-unknown)
         ;; (magit-blame-summary themian-unknown)
         (magit-branch-current magit-branch-local (:weight bold))
         (magit-branch-local themian-item)
         (magit-branch-remote nil (:foreground ,cyan :slant italic))
         (magit-branch-remote-head magit-branch-remote (:weight bold))
         (magit-branch-upstream themian-unknown)
         ;; (magit-cherry-equivalent themian-unknown)
         ;; (magit-cherry-unmatched themian-unknown)
         (magit-diff-added diff-added)
         (magit-diff-added-highlight magit-diff-added)
         ;; (magit-diff-base themian-unknown)
         ;; (magit-diff-base-highlight themian-unknown)
         (magit-diff-conflict-heading themian-warning)
         (magit-diff-context diff-context)
         (magit-diff-context-highlight region)
         (magit-diff-file-heading nil)
         (magit-diff-file-heading-highlight themian-strong)
         (magit-diff-file-heading-selection themian-unknown)
         (magit-diff-hunk-heading nil (:foreground ,base+1 :background ,base-3
                                       :slant italic))
         (magit-diff-hunk-heading-highlight nil (:foreground ,base+2
                                                 :background ,base-2
                                                 :slant normal))
         (magit-diff-hunk-heading-selection themian-unknown)
         (magit-diff-hunk-region themian-unknown)
         ;; (magit-diff-lines-boundary themian-unknown)
         ;; (magit-diff-lines-heading themian-unknown)
         ;; (magit-diff-our themian-unknown)
         ;; (magit-diff-our-highlight themian-unknown)
         (magit-diff-removed diff-removed)
         (magit-diff-removed-highlight magit-diff-removed)
         ;; (magit-diff-revision-summary themian-unknown)
         ;; (magit-diff-revision-summary-highlight themian-unknown)
         ;; (magit-diff-their themian-unknown)
         ;; (magit-diff-their-highlight themian-unknown)
         (magit-diff-whitespace-warning themian-warning)
         (magit-diffstat-added nil (:foreground ,green))
         (magit-diffstat-removed nil (:foreground ,red))
         (magit-dimmed themian-unknown)
         (magit-filename themian-item)
         (magit-hash themian-weak)
         (magit-head themian-unknown)
         (magit-header-line themian-heading)
         (magit-header-line-key themian-unknown)
         (magit-header-line-log-select themian-unknown)
         (magit-keyword themian-unknown)
         (magit-keyword-squash themian-warning)
         (magit-log-author themian-item)
         (magit-log-date themian-weak)
         (magit-log-graph themian-subtle)
         (magit-mode-line-process themian-warning)
         (magit-mode-line-process-error themian-error)
         ;; (magit-process-ng themian-unknown)
         ;; (magit-process-ok themian-unknown)
         (magit-reflog-amend nil (:foreground ,cyan))
         (magit-reflog-checkout nil (:foreground ,green))
         (magit-reflog-cherry-pick themian-unknown)
         (magit-reflog-commit nil (:foreground ,blue))
         (magit-reflog-merge nil (:foreground ,yellow))
         (magit-reflog-other themian-unknown)
         (magit-reflog-rebase magit-reflog-merge)
         (magit-reflog-remote magit-reflog-checkout)
         (magit-reflog-reset nil (:foreground ,orange :weight bold))
         (magit-refname nil (:foreground ,green :weight bold))
         (magit-refname-pullreq magit-refname)
         (magit-refname-stash magit-refname)
         (magit-refname-wip magit-refname)
         (magit-section-heading themian-heading)
         (magit-section-heading-selection themian-unknown)
         (magit-section-highlight nil (:background ,base-3))
         (magit-section-secondary-heading themian-unknown)
         ;; (magit-sequence-done themian-unknown)
         ;; (magit-sequence-drop themian-unknown)
         ;; (magit-sequence-exec themian-unknown)
         ;; (magit-sequence-head themian-unknown)
         ;; (magit-sequence-onto themian-unknown)
         ;; (magit-sequence-part themian-unknown)
         ;; (magit-sequence-pick themian-unknown)
         ;; (magit-sequence-stop themian-unknown)
         ;; (magit-signature-bad themian-unknown)
         ;; (magit-signature-error themian-unknown)
         ;; (magit-signature-expired themian-unknown)
         ;; (magit-signature-expired-key themian-unknown)
         ;; (magit-signature-good themian-unknown)
         ;; (magit-signature-revoked themian-unknown)
         ;; (magit-signature-untrusted themian-unknown)
         ;; (magit-tag themian-unknown)
         ;; (markdown-blockquote-face themian-unknown)
         ;; (markdown-bold-face themian-unknown)
         ;; (markdown-code-face themian-unknown)
         ;; (markdown-comment-face themian-unknown)
         ;; (markdown-footnote-marker-face themian-unknown)
         ;; (markdown-footnote-text-face themian-unknown)
         ;; (markdown-gfm-checkbox-face themian-unknown)
         ;; (markdown-header-delimiter-face themian-unknown)
         ;; (markdown-header-face themian-unknown)
         ;; (markdown-header-face-1 themian-unknown)
         ;; (markdown-header-face-2 themian-unknown)
         ;; (markdown-header-face-3 themian-unknown)
         ;; (markdown-header-face-4 themian-unknown)
         ;; (markdown-header-face-5 themian-unknown)
         ;; (markdown-header-face-6 themian-unknown)
         ;; (markdown-header-rule-face themian-unknown)
         ;; (markdown-highlight-face themian-unknown)
         ;; (markdown-hr-face themian-unknown)
         ;; (markdown-html-attr-name-face themian-unknown)
         ;; (markdown-html-attr-value-face themian-unknown)
         ;; (markdown-html-entity-face themian-unknown)
         ;; (markdown-html-tag-delimiter-face themian-unknown)
         ;; (markdown-html-tag-name-face themian-unknown)
         ;; (markdown-inline-code-face themian-unknown)
         ;; (markdown-italic-face themian-unknown)
         ;; (markdown-language-info-face themian-unknown)
         ;; (markdown-language-keyword-face themian-unknown)
         ;; (markdown-line-break-face themian-unknown)
         ;; (markdown-link-face themian-unknown)
         ;; (markdown-link-title-face themian-unknown)
         ;; (markdown-list-face themian-unknown)
         ;; (markdown-markup-face themian-unknown)
         ;; (markdown-math-face themian-unknown)
         ;; (markdown-metadata-key-face themian-unknown)
         ;; (markdown-metadata-value-face themian-unknown)
         ;; (markdown-missing-link-face themian-unknown)
         ;; (markdown-plain-url-face themian-unknown)
         ;; (markdown-pre-face themian-unknown)
         ;; (markdown-reference-face themian-unknown)
         ;; (markdown-strike-through-face themian-unknown)
         ;; (markdown-table-face themian-unknown)
         ;; (markdown-url-face themian-unknown)
         ;; (menu themian-unknown)
         ;; (message-cited-text-1 themian-unknown)
         ;; (message-cited-text-2 themian-unknown)
         ;; (message-cited-text-3 themian-unknown)
         ;; (message-cited-text-4 themian-unknown)
         ;; (message-header-cc themian-unknown)
         ;; (message-header-name themian-unknown)
         ;; (message-header-newsgroups themian-unknown)
         ;; (message-header-other themian-unknown)
         ;; (message-header-subject themian-unknown)
         ;; (message-header-to themian-unknown)
         ;; (message-header-xheader themian-unknown)
         ;; (message-mml themian-unknown)
         ;; (message-separator themian-unknown)
         ;; (mm-command-output themian-unknown)
         (mode-line nil (:foreground ,base+3 :background ,base-2))
         (mode-line-buffer-id nil)        ; overidden by `powerline-active1'
         (mode-line-buffer-id-inactive nil) ; overidden by `powerline-inactive1' 
         (mode-line-emphasis themian-warning)
         (mode-line-highlight themian-important)
         (mode-line-inactive themian-weak (:foreground ,base+2 :background ,base-3))
         ;; (mouse themian-unknown)
         ;; (mouse-drag-and-drop-region themian-unknown)
         ;; (next-error themian-unknown)
         ;; (nobreak-hyphen themian-unknown)
         ;; (nobreak-space themian-unknown)
         (org-agenda-calendar-event themian-unknown)
         (org-agenda-calendar-sexp (themian-strong) (:foreground ,green))
         (org-agenda-clocking themian-important)
         (org-agenda-column-dateline themian-unknown)
         (org-agenda-current-time themian-strong)
         (org-agenda-date nil)
         (org-agenda-date-today (themian-heading themian-strong))
         (org-agenda-date-weekend themian-weak)
         (org-agenda-diary themian-unknown)
         (org-agenda-dimmed-todo-face nil)
         (org-agenda-done themian-weak)
         (org-agenda-filter-category themian-weak)
         (org-agenda-filter-effort themian-weak)
         (org-agenda-filter-regexp themian-weak)
         (org-agenda-filter-tags themian-weak)
         (org-agenda-restriction-lock themian-unknown)
         (org-agenda-structure themian-heading)
         (org-archived themian-weak)
         (org-block nil (:background ,base-5))
         (org-block-begin-line org-drawer)
         (org-block-end-line org-drawer)
         (org-checkbox nil)
         (org-checkbox-statistics-done themian-weak (:height 0.8))
         (org-checkbox-statistics-todo themian-strong (:height 0.8))
         (org-clock-overlay themian-unknown)
         (org-code themian-strong)
         (org-column nil)
         (org-column-title themian-important)
         (org-date themian-strong (:foreground ,cyan))
         (org-date-selected themian-important)
         ;; org-default is a default face so we can't use inheritance
         (org-default nil ,(when themian-org-mode-variable-pitch
                             (face-attr-construct 'variable-pitch)))
         (org-dispatcher-highlight themian-unknown)
         (org-document-info themian-item)
         (org-document-info-keyword themian-weak)
         (org-document-title themian-strong (:height 1.2))
         ,(if themian-org-mode-emphasize-todo
              `(org-done themian-strong (:foreground ,green :height 0.8 :strike-through t))
            `(org-done nil (:foreground ,green :height 0.8)))
         (org-drawer themian-subtle (:slant normal))
         (org-ellipsis themian-subtle)
         (org-footnote (themian-weak link))
         (org-formula (themian-weak org-table))
         (org-headline-done org-done)
         (org-headline-todo org-todo)
         (org-hide nil (:foreground ,base-4))
         (org-indent org-hide)
         (org-latex-and-related themian-unknown)
         (org-level-1 themian-heading)
         (org-level-2 org-level-1)
         (org-level-3 org-level-1)
         (org-level-4 org-level-1)
         (org-level-5 org-level-1)
         (org-level-6 org-level-1)
         (org-level-7 org-level-1)
         (org-level-8 org-level-1)
         (org-link link)
         (org-list-dt themian-item)
         (org-macro themian-item)
         (org-meta-line themian-weak)
         (org-mode-line-clock themian-unknown)
         (org-mode-line-clock-overrun themian-unknown)
         (org-priority themian-weak (:foreground ,cyan :height 0.8))
         (org-property-value nil)
         (org-quote themian-weak (:slant italic))
         (org-scheduled themian-item)
         (org-scheduled-previously (org-warning themian-strong))
         (org-scheduled-today org-scheduled)
         (org-sexp-date org-date)
         (org-special-keyword themian-weak)
         (org-table nil (:foreground ,cyan :background ,base-5))
         (org-table-header themian-unknown)
         (org-tag themian-subtle (:height 0.9))
         (org-tag-group themian-unknown)
         (org-target themian-unknown)
         (org-time-grid themian-weak)
         ,(if themian-org-mode-emphasize-todo
              `(org-todo themian-strong (:foreground ,yellow :height 0.8))
            `(org-todo nil (:foreground ,yellow :height 0.8)))
         (org-upcoming-deadline (org-warning themian-subtle))
         (org-upcoming-distant-deadline themian-unknown)
         (org-verbatim org-code)
         (org-verse org-quote)
         (org-warning nil (:foreground ,orange)) ; really for deadlines
         (outline-1 org-level-1)
         (outline-2 org-level-2)
         (outline-3 org-level-3)
         (outline-4 org-level-4)
         (outline-5 org-level-5)
         (outline-6 org-level-6)
         (outline-7 org-level-7)
         (outline-8 org-level-8)
         ;; (package-description themian-unknown)
         ;; (package-help-section-name themian-unknown)
         ;; (package-name themian-unknown)
         ;; (package-status-avail-obso themian-unknown)
         ;; (package-status-available themian-unknown)
         ;; (package-status-built-in themian-unknown)
         ;; (package-status-dependency themian-unknown)
         ;; (package-status-disabled themian-unknown)
         ;; (package-status-external themian-unknown)
         ;; (package-status-held themian-unknown)
         ;; (package-status-incompat themian-unknown)
         ;; (package-status-installed themian-unknown)
         ;; (package-status-new themian-unknown)
         ;; (package-status-unsigned themian-unknown)
         (powerline-active0 themian-unknown)
         (powerline-active1 themian-strong (:foreground ,blue :background ,base-2))
         (powerline-active2 nil (:background ,base-2))
         (powerline-inactive0 themian-unknown)
         (powerline-inactive1 themian-weak (:background ,base-3))
         (powerline-inactive2 nil (:background ,base-3))
         ;; (query-replace themian-unknown)
         ;; (read-multiple-choice-face themian-unknown)
         ;; (rectangle-preview themian-unknown)
         ;; (rmail-header-name themian-unknown)
         ;; (rmail-highlight themian-unknown)
         ;; (scroll-bar themian-unknown)
         ;; (show-paren-match themian-unknown)
         ;; (show-paren-match-expression themian-unknown)
         ;; (show-paren-mismatch themian-unknown)
         ;; (shr-abbreviation themian-unknown)
         ;; (shr-link themian-unknown)
         ;; (shr-selected-link themian-unknown)
         ;; (shr-strike-through themian-unknown)
         ;; (smerge-base themian-unknown)
         ;; (smerge-lower themian-unknown)
         ;; (smerge-markers themian-unknown)
         ;; (smerge-refined-added themian-unknown)
         ;; (smerge-refined-changed themian-unknown)
         ;; (smerge-refined-removed themian-unknown)
         ;; (smerge-upper themian-unknown)
         ;; (sp-pair-overlay-face themian-unknown)
         ;; (sp-show-pair-enclosing themian-unknown)
         ;; (sp-show-pair-match-content-face themian-unknown)
         ;; (sp-show-pair-match-face themian-unknown)
         ;; (sp-show-pair-mismatch-face themian-unknown)
         ;; (sp-wrap-overlay-closing-pair themian-unknown)
         ;; (sp-wrap-overlay-face themian-unknown)
         ;; (sp-wrap-overlay-opening-pair themian-unknown)
         ;; (sp-wrap-tag-overlay-face themian-unknown)
         ;; (spaceline-all-the-icons-info-face themian-unknown)
         ;; (spaceline-all-the-icons-sunrise-face themian-unknown)
         ;; (spaceline-all-the-icons-sunset-face themian-unknown)
         (spaceline-evil-emacs nil (:background ,red-bg))
         (spaceline-evil-insert nil (:background ,green-bg))
         (spaceline-evil-motion nil (:background ,cyan-bg))
         (spaceline-evil-normal nil (:background ,blue-bg))
         (spaceline-evil-replace nil (:background ,orange-bg))
         (spaceline-evil-visual nil (:background ,violet-bg))
         (spaceline-flycheck-error themian-error)
         (spaceline-flycheck-info themian-item)
         (spaceline-flycheck-warning themian-warning)
         (spaceline-highlight-face themian-unknown)
         (spaceline-modified themian-unknown)
         (spaceline-python-venv themian-unknown)
         (spaceline-read-only themian-unknown)
         (spaceline-unmodified themian-unknown)
         ;; (speedbar-button-face themian-unknown)
         ;; (speedbar-directory-face themian-unknown)
         ;; (speedbar-file-face themian-unknown)
         ;; (speedbar-highlight-face themian-unknown)
         ;; (speedbar-selected-face themian-unknown)
         ;; (speedbar-separator-face themian-unknown)
         ;; (speedbar-tag-face themian-unknown)
         ;; (straight-process-command themian-unknown)
         ;; (straight-process-error themian-unknown)
         ;; (tab-bar themian-unknown)
         ;; (tab-bar-tab themian-unknown)
         ;; (tab-bar-tab-inactive themian-unknown)
         ;; (tab-line themian-unknown)
         ;; (tabulated-list-fake-header themian-unknown)
         (term nil (:inherit default))
         (term-color-black nil (:foreground ,base-4))
         (term-color-red nil (:foreground ,red))
         (term-color-green nil (:foreground ,green))
         (term-color-yellow nil (:foreground ,yellow))
         (term-color-blue nil (:foreground ,blue))
         (term-color-magenta nil (:foreground ,magenta))
         (term-color-cyan nil (:foreground ,cyan))
         (term-color-white nil (:foreground ,base+4))
         ;; (tool-bar themian-unknown)
         ;; (transient-active-infix themian-unknown)
         ;; (transient-amaranth themian-unknown)
         ;; (transient-argument themian-unknown)
         ;; (transient-blue themian-unknown)
         ;; (transient-disabled-suffix themian-unknown)
         ;; (transient-enabled-suffix themian-unknown)
         ;; (transient-heading themian-unknown)
         ;; (transient-inactive-argument themian-unknown)
         ;; (transient-inactive-value themian-unknown)
         ;; (transient-inapt-suffix themian-unknown)
         ;; (transient-key themian-unknown)
         ;; (transient-mismatched-key themian-unknown)
         ;; (transient-nonstandard-key themian-unknown)
         ;; (transient-pink themian-unknown)
         ;; (transient-red themian-unknown)
         ;; (transient-separator themian-unknown)
         ;; (transient-teal themian-unknown)
         ;; (transient-unreachable themian-unknown)
         ;; (transient-unreachable-key themian-unknown)
         ;; (transient-value themian-unknown)
         ;; (tty-menu-disabled-face themian-unknown)
         ;; (tty-menu-enabled-face themian-unknown)
         ;; (tty-menu-selected-face themian-unknown)
         ;; (vc-conflict-state themian-unknown)
         ;; (vc-edited-state themian-unknown)
         ;; (vc-locally-added-state themian-unknown)
         ;; (vc-locked-state themian-unknown)
         ;; (vc-missing-state themian-unknown)
         ;; (vc-needs-update-state themian-unknown)
         ;; (vc-removed-state themian-unknown)
         ;; (vc-state-base themian-unknown)
         ;; (vc-up-to-date-state themian-unknown)
         ;; (w3m-haddock-heading-face themian-unknown)
         (wgrep-delete-face themian-warning)
         (wgrep-done-face (themian-item themian-strong))
         (wgrep-face themian-important)
         (wgrep-file-face wgrep-face)
         (wgrep-reject-face themian-error)
         ;; (which-func themian-unknown)
         (which-key-command-description-face themian-item)
         (which-key-docstring-face themian-unknown)
         (which-key-group-description-face nil (:foreground ,orange))
         (which-key-highlighted-command-face themian-unknown)
         (which-key-key-face font-lock-constant-face)
         (which-key-local-map-description-face which-key-command-description-face)
         (which-key-note-face themian-weak)
         (which-key-separator-face themian-weak)
         (which-key-special-key-face themian-unknown)
         (whitespace-big-indent (themian-error themian-important))
         (whitespace-empty (themian-warning themian-important))
         (whitespace-hspace whitespace-space)
         (whitespace-indentation whitespace-space)
         (whitespace-line (themian-error themian-important))
         (whitespace-newline whitespace-space)
         (whitespace-space themian-subtle)
         (whitespace-space-after-tab (themian-warning themian-important))
         (whitespace-space-before-tab (themian-error themian-important))
         (whitespace-tab whitespace-space)
         (whitespace-trailing (themian-error themian-important))    
         ;; (widget-button themian-unknown)
         ;; (widget-button-pressed themian-unknown)
         ;; (widget-documentation themian-unknown)
         ;; (widget-field themian-unknown)
         ;; (widget-inactive themian-unknown)
         ;; (widget-single-line-field themian-unknown)
         ;; (window-divider themian-unknown)
         ;; (window-divider-first-pixel themian-unknown)
         ;; (window-divider-last-pixel themian-unknown)
         ;; (winum-face themian-unknown)
         ;; (xref-file-header themian-unknown)
         ;; (xref-line-number themian-unknown)
         ;; (xref-match themian-unknown)
         ;; (yaml-tab-face themian-unknown)
         ;; (yas--field-debug-face themian-unknown)
         ;; (yas-field-highlight-face themian-unknown)
         ))))))


;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))


(provide 'themian-theme)

;;; themian-theme.el ends here
